---
title: "Informacje ogólne"
---

## {{< var main.nazwa >}}

Kod: {{< var main.kod >}}

Semestr {{< var main.semestr >}} {{< var main.rok >}},

{{< var main.uczelnia >}}

Podstawowe informacje znajdziesz w [sylabusie](/sylabus).

Ciekawe książki i strony internetowe zamieszczone zostały w zakładce [książki](/ksiazki). 
Jeśli chciał(a)byś coś dodać prześlij informację przez MS teams.

## Kalendarz

#### Wykład 

Wykład jest realizowany w trybie hybrydowym.
Jest on NIEOBOWIĄZKOWY i odbywa się w sali C5D.

1. 02-10-2023 (poniedziałek) 11:40-13:20 - <del> Wykład 1 </del>

Historia klasycznego i kwantowego komputera i jego zastosowania. Efekty kwantowe wykorzystywane do przyśpieszenia obliczeń.

Realizacja:

- Zna i rozumie koncepcje działania komputera klasycznego i kwantowego
- Rozumie potrzebę i możliwości zastosowania komputerów kwantowych
- formułuje problem biznesowy wraz z jego informatycznym rozwiązaniem
- uzupełniania wiedzę teoretyczną jak i praktyczną, w zakresie teorii, programowania, modelowania, nowych technologii informatycznych z wykorzystaniem kwantowego uczenia maszynowego

2. 09-10-2023 (poniedziałek) 11:40-13:20 - <del> Wykład 2 </del>

Klasyczne bramki logiczne - algebra Boola, szyfrowanie

Realizacja:

- Zna i rozumie koncepcje działania komputera klasycznego i kwantowego
- Rozumie potrzebę i możliwości zastosowania komputerów kwantowych


3. 16-10-2023 (poniedziałek) 11:40-13:20 - <del> Wykład 3 </del>

Przestrzenie wektorowe, stany kwantowe, reprezentacja klasycznych i kwantowych bitów

4. 23-10-2023 (poniedziałek) 11:40-13:20 - <del> Wykład 4 </del>

Kwantowe bramki logiczne w prostych algorytmach i obwodach kwantowych

Realizacja:

- Potrafi stworzyć proste algorytmy z wykorzystaniem kwantowych bramek logicznych

5. 30-10-2023 (poniedziałek) 11:40-13:20 - <del> Wykład 5 </del>

DZIEŃ WOLNY

Kwantowy Machine Learning w biznesie - metody i implementacje

#### Laboratoria

Wszystkie laboratoria odbywają się w sali C5D.

1. 06-11-2023 (poniedziałek) 11:40-13:20 - <del>Lab1</del>

Przygotowanie środowiska programistycznego python z wykorzystaniem narzędzia Docker

2. 13-11-2023 (poniedziałek) 11:40-13:20 - <del>Lab2</del>

Kwantowe bity z wykorzystaniem biblioteki IBM Qiskit i Pennylane

3. 20-11-2023 (poniedziałek) 11:40-13:20 - <del>Lab3</del>

Jedno - kubitowe bramki logiczne

4. 27-11-2023 (poniedziałek) 11:40-13:20 - <del>Lab4</del>

Wielokubitowe bramki logiczne

5. 04-12-2023 (poniedziałek) 11:40-13:20 - <del>Lab5</del>

Algorytm faktoryzacji Shora, przeszukiwanie wg algorytmu Grovera.

6. 11-12-2023 (poniedziałek) 11:40-13:20 - <del>Lab6</del>

Klasyczny i kwantowy perceptron - realizacja w bibliotece qiskit

7. 18-12-2023 (poniedziałek) 11:40-13:20 - <del>Lab7</del>

Variational quantum classifiers - klasyfikacja danych iris

8. 08-01-2024 (poniedziałek) 11:40-13:20 - Lab8

klasyfikacja danych MNIST z wykorzystaniem biblioteki PyTorch Quantum

9. 15-01-2024 (poniedziałek) 11:40-13:20 - Lab9

Algorytm qPCA z wykorzystaniem do modelowania cen instrumentów finansowych

10. 22-01-2024 (poniedziałek) 11:40-13:20 - Lab10

Realizacje kwantowych sztucznych sieci neuronowych - wprowadzenie

## Technologie

Uczestnicząc w zajęciach musisz opanować i przynajmniej w podstawowym zakresie posługiwać się następującymi technologiami informatycznymi:

1. Algebra liniowa - wektory, macierze, baza, iloczyn skalarny, iloczyn tensorowy
2. Python, Jupyter notebook, Jupyter lab, Colab
3. Algorytmy sieci neuronowych i uczenia maszynowego w procesie klasyfikacji binarnej

## QPoland 

[QPoland](https://qworld.net/qpoland/) jest cześcią międzynarodowej sieci [QWorld](https://qworld.net).

Zapraszamy do wspólnego poszerzania wiedzy. [Szczegóły](https://qworld.net/join-us/) 
> QWorld is a global network of individuals, groups, and communities collaborating on education and implementation of quantum technologies and research activities.