---
title: Książki i strony WWW
---

## Książki 

<div id="QC">
### Obliczenia kwantowe (Quantum Computing)
</div>
1. Chris Bernhardt, _Obliczenia kwantowe dla każdego_. PWN 2020

> Wyjaśnienie _jak to działa_ w obliczeniach kwantowych.

2. Michel Le Bellac, _Wstęp do informatyki kwantowej_. PWN 2011

> Trudniejsza, dużo matematyki i fizyki. 

3. Thomas G. Wong, _Introduction to Classical and Quantum Computing_. Rooted Grove 2022.

> Bardzo dobra!, dużo przykładów, dużo ciekawych informacji wyjaśnianych bardzo szczegółowo. 
 
4. A. Jacquier, O. Kondratyev, _Quantum Machine Learning and Optimisation in Finance. On the Road to Quantum Advantage_.

5. P. Gawron, M. Cholewa, ... _Rewolucja stanu. Fantastyczne wprowadzenie do informatyki kwantowej_. Quantumz.io 2021

6. A. Saxena, J. Mancilla, I. Montalban, C. Pere, _Financial Modeling Using Quantum Computing_. Packt 2023

7. M. Schuld, F. Petruccione, _Machine Learning with Quantum Computers_, Springer 2021.

<div id="AI">
### AI 
</div>
1. L. Moroney, Sztuczna inteligencja i uczenie maszynowe dla programistów. Praktyczny przewodnik po sztucznej inteligencji. Helion 2021.
[Zobacz opis](http://helion.pl/view/111546/szinum.html) lub [Kup e-book](http://helion.pl/add111546~szinum_ebook)

2. Bruce, Bruce, Gedeck, Statystyka praktyczna w data science. Wydanie II. Helion. 2021.

## Strony WWW

1. Peter Shor [Wykład](https://math.mit.edu/~shor/435-LN/)

### Pakiety Python

1. [Qiskit](http://www.numpy.org)
2. [PennyLane](http://www.scipy.org)

### Pakiety Julia 

1. [Yao]()
2. [QAOA]()

### Edytory tekstu

1. [Notepad++](https://notepad-plus-plus.org/download)
2. [Sublime Text](https://www.sublimetext.com)
3. [Visual Studio Code](https://code.visualstudio.com)

### Markdown

1. [MD](http://daringfireball.net/projects/markdown/)

### Filmy

1. [Wprowadzenie do obliczeń kwantowych](https://www.youtube.com/watch?v=-UlxHPIEVqA)
2. QPoland, Bronze, [Warsztaty z programowania komputerów kwantowych 2023](https://www.youtube.com/watch?v=nDCROyWULkw&list=PLjZhz-aJHvA1q5DcsR_Y1XvsF2juz0FoN&index=2)

